"""initial tables

Revision ID: dd3c7466d729
Revises: 
Create Date: 2026-06-27 18:49:35.885596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd3c7466d729'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('client_config',
    sa.Column('client_key', sa.String(length=255), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('refill_rate', sa.Float(), nullable=False),
    sa.Column('window_size', sa.Integer(), nullable=False),
    sa.Column('algorithm', sa.Enum('token_bucket', 'sliding_window', name='algorithmtype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('client_key')
    )
    op.create_table('request_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_key', sa.String(length=255), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('allowed', sa.Integer(), nullable=False),
    sa.Column('denied', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_stats_client_key'), 'request_stats', ['client_key'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_stats_client_key'), table_name='request_stats')
    op.drop_table('request_stats')
    op.drop_table('client_config')
    # ### end Alembic commands ###
